networks:
  default:
    name: kafka-spark-network
    external: true
services:
  kafka_producer_load:
    image: kafka_producer_load
    container_name: kafka_producer_load
    env_file:
      - .env
    build:
      context: .
      dockerfile: ./docker_compose/kafka_producer_load.Dockerfile
    environment:
      PYTHONPATH: /app/${PROJECT_NAME}/src   
    volumes:
      - ./logs:/app/logs
      - ./src:/app/${PROJECT_NAME}/src
      - .env:/app/${PROJECT_NAME}/.env
  kafka_producer_gas:
    image: kafka_producer_gas
    container_name: kafka_producer_gas
    env_file:
      - .env
    build:
      context: .
      dockerfile: ./docker_compose/kafka_producer_gas.Dockerfile
    environment:
      PYTHONPATH: /app/${PROJECT_NAME}/src
    volumes:
      - ./logs:/app/logs
      - ./src:/app/${PROJECT_NAME}/src
      - .env:/app/${PROJECT_NAME}/.env    
  magic:
    image: mageai/mageai:latest
    command: mage start ${PROJECT_NAME}
    env_file:
      - .env
    build:
      context: .
      dockerfile: ./docker_compose/mage.Dockerfile
    environment:
      USER_CODE_PATH: ./home/src/${PROJECT_NAME}
    ports:
      - 6789:6789   
    volumes:
      - .:/home/src/${PROJECT_NAME}
    restart: on-failure:5