networks:
  default:
    name: kafka-spark-network
    external: true
services:
  kafka_producer:
    image: kafka_producer
    container_name: kafka_producer
    env_file:
      - .env
    build:
      context: .
      dockerfile: ./docker_compose/kafka_producer.Dockerfile
    volumes:
      - ./logs:/app/logs
      - ./src:/app/src
  magic:
    image: mageai/mageai:latest
    command: mage start ${PROJECT_NAME}
    env_file:
      - .env
    build:
      context: .
      dockerfile: ./docker_compose/mage.Dockerfile
    environment:
      USER_CODE_PATH: ./home/src/${PROJECT_NAME}
    ports:
      - 6789:6789   
    volumes:
      - .:/home/src/${PROJECT_NAME}
    restart: on-failure:5