networks:
  default:
    name: kafka-spark-network
    external: true
services:
  kafka_producer_load:
    container_name: kafka_producer_load
    env_file:
      - .env
    build:
      context: .
      dockerfile: ./docker_compose/kafka_producer_load.Dockerfile
    environment:
      PYTHONPATH: /app/${PROJECT_NAME}   
    volumes:
      - ./logs:/app/logs
      - ./src:/app/${PROJECT_NAME}/src
      - .env:/app/${PROJECT_NAME}/.env
   
  kafka_producer_gas:
    container_name: kafka_producer_gas
    env_file:
      - .env
    build:
      context: .
      dockerfile: ./docker_compose/kafka_producer_gas.Dockerfile
    environment:
      PYTHONPATH: /app/${PROJECT_NAME}
    volumes:
      - ./logs:/app/logs
      - ./src:/app/${PROJECT_NAME}/src
      - .env:/app/${PROJECT_NAME}/.env    
